apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  rules:
  - host: babypointapp.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80