apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
spec:
 rules:
   - host: www.babypointapp.com
     http:
       paths:
         - path: /
           backend:
             serviceName: web
             servicePort: 80